[package]
name = "stitch-animation"
version = "0.1.1"
authors = ["The8472 <git@infinite-source.de>"]

[profile.release]
lto = true

[dependencies]
ffmpeg = {version = "0.2.0-alpha.2", git = "https://github.com/meh/rust-ffmpeg.git" }

[replace]
"ffmpeg-sys:3.2.1" = {path = "./ffmpeg-sys"}
